server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
              - Path=/restaurants/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/deliveries/**
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/track/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka