spring:
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka