spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/deepa-ganesh/food-delivery-backend-cloud-native.git
          search-paths: config-files
          default-label: main